name: Build Dot Net Framework App

on: 
  push:
    branches: workflow_dispatch
      

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    name: CI Build dotnet app
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      - name: dot net build
        uses: 

   
    
      
  
    
