name: Build Dot Net Framework App

on: 
  push:
    branches: master
      

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest
    name: CI Build dotnet app
    steps:
      
      - name: checking out code
        uses: actions/checkout@v2
      
      - name: dot net compile tool
        uses: microsoft/setup-msbuild@v1
      
      # Step 3: Restore NuGet packages
      - name: Restore NuGet Packages
        run: nuget restore ./SomeConsoleApplication.sln
      
      # Step 4: Build the solution
      - name: Build Solution
        run: msbuild YourSolution.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifact
          path: "./_build" 

   
    
      
  
    
